services:
  invoice:
    image: ghcr.io/thi-projekte/restockoffice-invoice:feature-invoice
    restart: unless-stopped

    networks:
      - nginx-proxy-manager
      - invoice-intern
    environment:
      RESTOCK_MAIL_SENDER: noreply@restockoffice.de
      RESTOCK_MAIL_REPLY_TO: support@restockoffice.de
      RESTOCK_MAIL_SUPPORT_EMAIL: support@restockoffice.de
      RESTOCK_MAIL_LOGO_URL: https://restockoffice.de/assets/logo_colored.png
      QUARKUS_MAILER_PASSWORD: ${QUARKUS_MAILER_PASSWORD}
      RESTOCK_MAIL_RESEND_BASE_URL: https://api.resend.com
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db-container:5432/invoices_db
      QUARKUS_DATASOURCE_USERNAME: reStockOffice
      QUARKUS_DATASOURCE_PASSWORD: reStockOffice123$
      QUARKUS_OIDC_AUTH_SERVER_URL: http://id.restockoffice.de/realms/restockoffice
    depends_on:
      - db-container

  db-container:
    image: postgres:15
    networks:
      - invoice-intern
    environment:
      POSTGRES_USER: reStockOffice
      POSTGRES_PASSWORD: reStockOffice123$
      POSTGRES_DB: invoices_db

    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
networks:
  nginx-proxy-manager:
    external: true
  invoice-intern:
    driver: bridge
