services:
  orders:
    image: ghcr.io/thi-projekte/restockoffice-orders:latest
    container_name: orders
    #ports:
    #  - "8081:8081"
    networks:
      - nginx-proxy-manager
      - orders
    environment:
      QUARKUS_HTTP_PORT: "8080"
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db-container:5432/orders_db
      QUARKUS_DATASOURCE_USERNAME: reStockOffice
      QUARKUS_DATASOURCE_PASSWORD: reStockOffice123$
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: update
      QUARKUS_OIDC_ENABLED: "true"
      QUARKUS_OIDC_TOKEN_AUDIENCE: account
      QUARKUS_OIDC_AUTH_SERVER_URL: https://id.restockoffice.de/realms/restockoffice
      QUARKUS_OIDC_CLIENT_ID: restock-orders
      QUARKUS_OIDC_CREDENTIALS_SECRET: "restock-secret"
      QUARKUS_OIDC_APPLICATION_TYPE: service
    depends_on:
      - db-container

  db-container:
    image: postgres:15
    container_name: db-container
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: reStockOffice
      POSTGRES_PASSWORD: reStockOffice123$
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - orders
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U reStockOffice" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  db_data:

networks:
  nginx-proxy-manager:
    external: true
  orders:
    external: false
    driver: bridge
