services:
  processengine:
    image: ghcr.io/thi-projekte/restockoffice-processengine:latest
    restart: unless-stopped
    environment:
      SERVER_FORWARD_HEADERS_STRATEGY: framework
      CORS_ORIGINS: https://app.restockoffice.de
      MAILSERVICE_BASE_URL: http://confirmation-mails:8081
    ports:
      - "${PROCESSENGINE_HTTP_PORT:-8080}:8080"
    networks:
      - default
      - nginx-proxy-manager
      - mailer

networks:
  nginx-proxy-manager:
    external: true
  mailer:
    external: true
