version: "3.8"

services:
  frontend:
    image: ghcr.io/thi-projekte/restockoffice-frontend:1.0.4
    container_name: restockoffice-frontend
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      - NODE_ENV=production