# Datenbank-Typ und Ort
quarkus.datasource.db-kind=postgresql


# Hibernate Einstellungen
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

# OIDC Sicherheit
quarkus.http.auth.permission.public.paths=/users,/users/*
quarkus.http.auth.permission.public.policy=permit

quarkus.http.cors=true
quarkus.http.cors.origins=https://app.restockoffice.de
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,HEAD
quarkus.http.cors.headers=Content-Type, Authorization, Accept, Origin, X-Requested-With
quarkus.http.cors.access-control-allow-credentials=true

quarkus.http.filter.cors.header."Access-Control-Allow-Origin"=https://app.restockoffice.de
quarkus.http.filter.cors.matches=/.*

quarkus.oidc.enabled=true
quarkus.oidc.auth-server-url=${OIDC_URL:https://id.restockoffice.de/realms/restockoffice}
quarkus.oidc.client-id=restockoffice-spa
quarkus.oidc.application-type=service
quarkus.http.auth.proactive=false
quarkus.oidc.token-validation-method=jwt
quarkus.oidc.token.issuer=any
quarkus.oidc.roles.source=accesstoken
quarkus.oidc.roles.role-claim-path=realm_access/roles