# Datenbank-Typ und Ort
quarkus.datasource.db-kind=postgresql


# Hibernate Einstellungen
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# OIDC Sicherheit
quarkus.http.auth.permission.public.paths=/users,/users/*
quarkus.http.auth.permission.public.policy=permit

quarkus.http.cors=true
quarkus.http.cors.origins=https://app.restockoffice.de
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,HEAD
quarkus.http.cors.headers=Content-Type, Authorization, Accept, Origin, X-Requested-With
quarkus.http.cors.access-control-allow-credentials=true

quarkus.http.filter.cors.header."Access-Control-Allow-Origin"=https://app.restockoffice.de
quarkus.http.filter.cors.matches=/.*