# Datenbank-Typ und Ort
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:default
quarkus.datasource.username=sa
quarkus.datasource.password=

# Hibernate Einstellungen
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# OIDC Sicherheit (damit die Endpunkte wissen, dass sie prüfen müssen)
quarkus.http.auth.permission.public.paths=/products,/products/*
quarkus.http.auth.permission.public.policy=permit