camunda.bpm:
  history-level: audit
  authorization:
    enabled: true
  filter:
    create: All tasks
  oauth2:
    identity-provider:
      # starter-security idP must be disabled
      enabled: false

spring:
  jersey:
    application-path: /engine-rest
  config:
    import:
      - optional:classpath:cibseven-webclient.yaml
      - optional:classpath:cibseven-webclient.properties

# Spring Boot Security configuration for Keycloak Identity Provider + OAuth2
spring.security:
  oauth2:
    client:
      registration:
        keycloak:
          clientId: cib-seven-local
          clientSecret: cib-seven-secret
          scope: openid,profile,email,offline_access,roles # 4
          authorization-grant-type: authorization_code
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
      provider:
        keycloak:
          issuer-uri: http://localhost:8180/realms/cib-seven
          authorization-uri: http://localhost:8180/realms/cib-seven/protocol/openid-connect/auth
          token-uri: http://localhost:8180/realms/cib-seven/protocol/openid-connect/token
          user-info-uri: http://localhost:8180/realms/cib-seven/protocol/openid-connect/userinfo
          jwk-set-uri: http://localhost:8180/realms/cib-seven/protocol/openid-connect/certs
          # set user-name-attribute one of: 
          # - sub                -> default; using keycloak ID as CIB seven user ID
          # - email              -> useEmailAsCamundaUserId=true
          # - preferred_username -> useUsernameAsCamundaUserId=true
          user-name-attribute: preferred_username
    resourceserver:
      jwt:
        principal-claim-name: preferred_username
        jwk-set-uri: http://localhost:8180/realms/cib-seven/protocol/openid-connect/certs
        #audiences: camunda-rest-api


logging:
  level:
    root: INFO

# CIB seven Keycloak Identity Provider Plugin
plugin.identity.keycloak:
  keycloakIssuerUrl: http://localhost:8180/realms/cib-seven
  keycloakAdminUrl: http://localhost:8180/admin/realms/cib-seven
  clientId: cib-seven-local
  clientSecret: cib-seven-secret
  useEmailAsCamundaUserId: false
  useUsernameAsCamundaUserId: true
  useGroupPathAsCamundaGroupId: true
  enforceSubgroupsInGroupQuery: true
  administratorGroupName: camunda-admin
  administratorUserId: demo
  disableSSLCertificateValidation: true

cibseven:
  bpm:
    oauth2:
      identity-provider:
        enabled: false
        group-name-attribute: 
  webclient:
    engineRest:
      url: http://localhost:8080
    authentication:
      tokenValidMinutes: 30
      tokenProlongMinutes: 10
    sso:
      active: true
      endpoints:
        authorization: http://localhost:8180/realms/cib-seven/protocol/openid-connect/auth
        token: http://localhost:8180/realms/cib-seven/protocol/openid-connect/token
        jwks: http://localhost:8180/realms/cib-seven/protocol/openid-connect/certs
        user: http://localhost:8180/realms/cib-seven/protocol/openid-connect/userinfo
      clientId: cib-seven-local
      clientSecret: cib-seven-secret
      scopes: openid email profile
      userIdProperty: preferred_username
      userNameProperty: name
      accessTokenToEngineRest: true
    bpm:
     provider: org.cibseven.webapp.providers.SevenProvider
    user:
     provider: org.cibseven.webapp.auth.KeycloakUserProvider

# Metrics & Health
management:
  endpoint.health.probes.enabled: true
  endpoints:
    web.exposure.include: env,health,info,metrics