quarkus.http.cors.enabled=true
quarkus.http.cors.origins=https://app.restockoffice.de
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,HEAD,PATCH
quarkus.http.cors.headers=content-type,authorization,accept,origin,x-requested-with
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.force-headers-on-exception=true

%dev.quarkus.http.port=8081
%dev.quarkus.http.cors.origins=http://localhost:5173,http://127.0.0.1:5173,https://app.restockoffice.de

%dev.quarkus.oidc.auth-server-url=http://localhost:8180/realms/restockoffice
%dev.quarkus.oidc.token.issuer=http://localhost:8180/realms/restockoffice
%dev.quarkus.oidc.client-id=restock-office-web
%dev.quarkus.oidc.application-type=service
%dev.quarkus.http.auth.proactive=false

processengine.abo-confirmation-start-url=http://processengine:8080/api/abo-confirmation-process/change
%dev.processengine.abo-confirmation-start-url=http://localhost:8080/api/abo-confirmation-process/change
processengine.abo-confirmation-window-duration=PT10M
%dev.processengine.abo-confirmation-window-duration=PT30S
deliveriesservice.base-url=${DELIVERIES_SERVICE_URL:https://restocker-deliveries.restockoffice.de}
