# Datenbankverbindung
#quarkus.datasource.db-kind=postgresql
#quarkus.datasource.jdbc.url=jdbc:postgresql://db-container:5432/orders_db
#quarkus.datasource.username=reStockOffice
#quarkus.datasource.password=reStockOffice123$

# Schema automatisch aktualisieren (nur Entwicklung)
#quarkus.hibernate-orm.database.generation=update

# Keycloak
quarkus.oidc.enabled=true
#quarkus.oidc.auth-server-url=${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
#quarkus.oidc.client-id=${KEYCLOAK_CLIENT_ID}
#quarkus.oidc.auth-server-url=http://localhost:8180/realms/cib-seven

#quarkus.oidc.auth-server-url=http://keycloak:8080/realms/cib-seven
#quarkus.oidc.client-id=cib-seven-local
#quarkus.oidc.credentials.secret=cib-seven-secret
# Gruppen als Rollen verwenden (behebt fehler in RolesAllowed)
#quarkus.oidc.roles.role-claim-path=groups

#quarkus.oidc.application-type=service
#quarkus.oidc.roles.source=accesstoken
#quarkus.oidc.roles.role-claim-path=realm_access.roles
#quarkus.oidc.roles.role-claim-path=realm_access/roles
#quarkus.oidc.roles.role-claim-path=roles
quarkus.http.port=8081


#quarkus.http.auth.permission.authenticated.paths=/orders/*
#quarkus.http.auth.permission.authenticated.policy=authenticated
#quarkus.http.auth.proactive=true

#quarkus.log.category."io.quarkus.security".level=DEBUG
#quarkus.log.category."io.quarkus.oidc".level=DEBUG

