# Datenbankverbindung
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/articles_db
quarkus.datasource.username=reStockOffice
quarkus.datasource.password=reStockOffice123$

# Schema automatisch aktualisieren (nur Entwicklung)
quarkus.hibernate-orm.database.generation=update

# Keycloak
#quarkus.oidc.devservices.enabled=false
#quarkus.keycloak.devservices.enabled=false
#quarkus.oidc.auth-server-url=${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
#quarkus.oidc.client-id=${KEYCLOAK_CLIENT_ID}
quarkus.oidc.auth-server-url=http://localhost:8180/realms/cib-seven
quarkus.oidc.client-id=cib-seven-local
quarkus.oidc.credentials.secret=cib-seven-secret
# Gruppen als Rollen verwenden (behebt fehler in RolesAllowed)
quarkus.oidc.roles.role-claim-path=groups

quarkus.oidc.application-type=service

