quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${CORS_ORIGINS:http://localhost:5173,http://127.0.0.1:5173,https://app.restockoffice.de}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,HEAD
quarkus.http.cors.headers=Content-Type, Authorization, Accept, Origin, X-Requested-With
quarkus.http.cors.access-control-allow-credentials=true

quarkus.oidc.auth-server-url=${QUARKUS_OIDC_AUTH_SERVER_URL:https://id.restockoffice.de/realms/restockoffice}
quarkus.oidc.client-id=${QUARKUS_OIDC_CLIENT_ID:restockoffice-spa}
quarkus.oidc.application-type=service
quarkus.http.auth.proactive=false

quarkus.rest-client.orders-service.url=${ORDERS_SERVICE_URL:https://orders.restockoffice.de}
quarkus.rest-client.users-service.url=${USERS_SERVICE_URL:https://users.restockoffice.de}
quarkus.rest-client.articles-service.url=${ARTICLES_SERVICE_URL:https://articles.restockoffice.de}
