services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.5
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "8180:8080"
    volumes:
      #- keycloak_data:/opt/keycloak/data
      - ./keycloak:/opt/keycloak/data/import
    networks:
      nginx-proxy-manager:
        aliases:
          - keycloak

volumes:
  keycloak_data:

networks:
  nginx-proxy-manager:
    external: true