services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.5
    container_name: restockoffice-keycloak
    command: start-dev
    environment:
      KC_HOSTNAME: id.restockoffice.de
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - nginx-proxy-manager

volumes:
  keycloak_data:

networks:
  nginx-proxy-manager:
    external: true