# Datenbank-Typ und Ort
quarkus.datasource.db-kind=postgresql

quarkus.native.resources.includes=products.json

# Hibernate Einstellungen
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# OIDC Sicherheit
quarkus.http.auth.permission.public.paths=/articles,/articles/*
quarkus.http.auth.permission.public.policy=permit