services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
