quarkus.http.auth.permission.public.paths=/emails/*
quarkus.http.auth.permission.public.policy=permit
quarkus.native.resources.includes=templates/*,examples/*

restock.mail.sender=${RESTOCK_MAIL_SENDER:noreply@restockoffice.de}
restock.mail.reply-to=${RESTOCK_MAIL_REPLY_TO:support@restockoffice.de}
restock.mail.support-email=${RESTOCK_MAIL_SUPPORT_EMAIL:support@restockoffice.de}
restock.mail.logo-url=${RESTOCK_MAIL_LOGO_URL:https://restockoffice.de/assets/logo_colored.png}
restock.mail.resend-api-key=${RESTOCK_MAIL_RESEND_API_KEY:}
restock.mail.resend-base-url=${RESTOCK_MAIL_RESEND_BASE_URL:https://api.resend.com}
