services:
  spa:
    image: ghcr.io/thi-projekte/restockoffice-spa:latest
    networks:
      - nginx-proxy-manager
    container_name: restockoffice-spa
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

networks:
  nginx-proxy-manager:
    external: true 
