
restock.mail.sender=${RESTOCK_MAIL_SENDER:noreply@restockoffice.de}
restock.mail.reply-to=${RESTOCK_MAIL_REPLY_TO:support@restockoffice.de}
restock.mail.support-email=${RESTOCK_MAIL_SUPPORT_EMAIL:support@restockoffice.de}
restock.mail.logo-url=${RESTOCK_MAIL_LOGO_URL:https://nbg1.your-objectstorage.com/restockoffice/assets/branding/logo_colored.png}
restock.mail.resend-api-key=${QUARKUS_MAILER_PASSWORD:}
restock.mail.resend-base-url=${RESTOCK_MAIL_RESEND_BASE_URL:https://api.resend.com}

invoice.logo.url=https://nbg1.your-objectstorage.com/restockoffice/assets/branding/logo_colored.jpg

quarkus.http.auth.permission.public.paths=/emails/*, /emails
quarkus.http.auth.permission.public.policy=permit


# Datenbank-Typ und Ort
quarkus.datasource.db-kind=postgresql

quarkus.datasource.devservices.enabled=false
%dev.quarkus.datasource.username=reStockOffice
%dev.quarkus.datasource.password=reStockOffice123$
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/invoices_db

# Hibernate Einstellungen
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.http.cors=true
quarkus.http.cors.origins=https://app.restockoffice.de
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,HEAD
quarkus.http.cors.headers=Content-Type, Authorization, Accept, Origin, X-Requested-With
quarkus.http.cors.access-control-allow-credentials=true

quarkus.http.filter.cors.header."Access-Control-Allow-Origin"=https://app.restockoffice.de
quarkus.http.filter.cors.matches=/.*
