name: Build and Push Keycloak Image

on:
  push:
    branches:
      - main
    paths:
      - 'keycloak/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./keycloak
          file: ./keycloak/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/restockoffice-keycloak:latest
            ghcr.io/${{ github.repository_owner }}/restockoffice-keycloak:${{ github.sha }}
